# Generated by Django 2.1.7 on 2019-02-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Utype', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
