# Generated by Django 2.1.7 on 2019-02-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0004_auto_20190224_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
