# Generated by Django 2.1.7 on 2019-02-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
