# Generated by Django 2.1.7 on 2019-02-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0007_auto_20190225_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meds',
        ),
    ]
