# Generated by Django 2.1.7 on 2019-02-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('Demo', '0013_auto_20190226_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractuser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='AbstractUser',
        ),
    ]
