# Generated by Django 2.1.7 on 2019-02-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('Demo', '0015_utype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utype',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='utype',
        ),
    ]
