# Generated by Django 2.1.7 on 2019-02-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0018_auto_20190227_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='kind',
        ),
    ]
