# Generated by Django 2.1.7 on 2019-02-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0021_salerm'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerm',
            name='utype',
            field=models.CharField(choices=[('S', 'Saler'), ('B', 'Buyer'), ('A', 'Agent')], max_length=1, null=True),
        ),
    ]
