# Generated by Django 2.1.7 on 2019-02-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0022_salerm_utype'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerm',
            name='Agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salerm',
            name='Buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salerm',
            name='Saler',
            field=models.BooleanField(default=False),
        ),
    ]
