# Generated by Django 2.1.7 on 2019-02-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0023_auto_20190227_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerm',
            name='utype',
        ),
        migrations.AlterField(
            model_name='salerm',
            name='Saler',
            field=models.BooleanField(default=True),
        ),
    ]
