# Generated by Django 2.1.7 on 2019-02-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0024_auto_20190227_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerm',
            name='user',
        ),
        migrations.DeleteModel(
            name='salerm',
        ),
    ]
