# Generated by Django 2.1.7 on 2019-02-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0027_auto_20190228_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='utype',
            field=models.CharField(choices=[('A', 'Agent'), ('B', 'Buyer'), ('S', 'Saler')], max_length=1),
        ),
    ]
