# Generated by Django 2.1.7 on 2019-02-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0029_remove_user_type_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_type',
        ),
    ]
