# Generated by Django 2.2.1 on 2019-05-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auther', models.CharField(max_length=50)),
                ('Content', models.CharField(max_length=1000)),
                ('Publish_date', models.DateTimeField(verbose_name='pubdate')),
            ],
        ),
    ]
