# Generated by Django 2.2.1 on 2019-05-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20190523_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pet_name',
            field=models.CharField(default='Not have any pet', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
