# Generated by Django 2.2.2 on 2019-06-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_redhat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Review',
            field=models.TextField(default='Anyting to review :)'),
        ),
    ]
