# Generated by Django 2.1.7 on 2019-02-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0012_auto_20190226_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='is_buyer',
            field=models.BooleanField(default=False, verbose_name='Buyer status'),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='is_saler',
            field=models.BooleanField(default=False, verbose_name='Sailer status'),
        ),
    ]
