# Generated by Django 2.1.7 on 2019-02-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0017_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='kind',
            field=models.CharField(max_length=23),
        ),
    ]
