# Generated by Django 2.1.7 on 2019-02-28 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Demo', '0026_is_agent_is_buyer_is_saler'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utype', models.CharField(default='S', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='is_agent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='is_buyer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='is_saler',
            name='user',
        ),
        migrations.DeleteModel(
            name='Is_agent',
        ),
        migrations.DeleteModel(
            name='Is_buyer',
        ),
        migrations.DeleteModel(
            name='Is_saler',
        ),
    ]
