# Generated by Django 2.1.7 on 2019-02-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0028_auto_20190228_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_type',
            name='user',
        ),
    ]
